APHive/APHive/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^members/', include('members.urls', namespace='members')),
    url(r'^apis/', include('apis.urls', namespace='apis')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

APHive/apis/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from apis.views import *

urlpatterns = patterns('',
	url(r'^$', ApiIndexView.as_view(), name='home'),
	url(r'^kitchensink/$', KitchenSinkView.as_view(), name='kitchensink'),
	url(r'^(?P<api_id>\d+)/$', ApiDetailView.as_view(), name='detail'),	
)

APHive/members/urls.py
from django.conf.urls import patterns, url
from members.views import *

urlpatterns = patterns('',
	url(r'^(?P<member_id>\d+)/$', MemberDetailView.as_view(), name='detail'),
)	

APHive/apis/models.py
from django.db import models
from members.models import Member

class Api(models.Model):
	def __unicode__(self):
		return self.title
	title = models.CharField(max_length=25)
	icon = models.ImageField(upload_to='apis/icons/')
	brief_desc = models.CharField(max_length=50)
	full_desc = models.TextField(max_length=250)
	author = models.ForeignKey(Member)

	

APHive/endpoints/models.py
from django.db import models
from apis.models import Api

class Endpoint(models.Model):
	HTTP_METHODS = (
		('GET','GET'),
		('POST','POST'),
		('PUT','PUT'),
		('DELETE','DELETE'),
	)

	def __unicode__(self):
		return method + ': ' + url
	url = models.URLField()
	api = models.ForeignKey(Api)
	method = models.CharField(choices=HTTP_METHODS, max_length=10, default='GET')	
	description = models.TextField(max_length=100)

APHive/members/models.py
from django.db import models

class Member(models.Model):
	def __unicode__(self):
		return self.full_name	
	@property
	def full_name(self):
		return self.first_name + ' ' + self.last_name 

	first_name = models.CharField(max_length=25)
	last_name = models.CharField(max_length=25)
	email = models.EmailField()
	joined = models.DateField()
	

APHive/reviews/models.py
from django.db import models
from apis.models import Api
from members.models import Member

class Review(models.Model):
	def __unicode__(self):
		return self.api.title
	text = models.TextField(max_length=500)
	api = models.ForeignKey(Api)
	writer = models.ForeignKey(Member)
	submitted = models.DateField()
	usability = models.NullBooleanField(null=True)
	documentation = models.NullBooleanField(null=True)
	reliability = models.NullBooleanField(null=True)

APHive/apis/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from apis.models import Api

class ApiDetailView(View):
	def get(self, request, api_id):
		api = get_object_or_404(Api, pk=api_id)
		context = {
			'api': api,
		}
		return render(request, 'api_detail.html', context)

class ApiIndexView(View):
	def get(self, request):
		apis = Api.objects.all()
		context = {
			'apis': apis,
		}
		return render(request, 'api_index.html', context)

class KitchenSinkView(View):
	def get(self, request):
		context = {}
		return render(request, 'kitchensink.html', context)

APHive/endpoints/views.py
from django.shortcuts import render

# Create your views here.

APHive/members/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from members.models import Member
from apis.models import Api

class MemberDetailView(View):
	def get(self, request, member_id):
		m = get_object_or_404(Member, pk=member_id)
		apis = Api.objects.filter(author_id=member_id)
		context = {
			'member': m,
			'apis' : apis,
		}
		return render(request, 'member_detail.html', context)

APHive/reviews/views.py
from django.shortcuts import render

APHive/APHive/templates/APHive/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
	<!-- css and metadata -->
	<head>
	    <meta charset="utf-8" />
	    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	    <title>{% block title %}This shouldnt be here{% endblock %}</title>
	    {% block css %}
            <link rel="stylesheet" href={% static "css/foundation.css" %} />
	    <link rel="stylesheet" href={% static "css/foundation-icons.css" %} />
	    <link rel="stylesheet" href={% static "css/normalize.css" %} />
	    <link rel="stylesheet" href={% static "APHive/css/style.css" %} />
	    <script src= {% static "js/modernizr.js" %}></script>
	    <script src= {% static "js/jquery.js" %}></script>
	    {% endblock css %}
	</head>
	<!-- content area -->
	<body>
	    <!-- navbar -->
	    {% include "navbar.html" %}

	    <!-- page-unique content -->
	    <div id="content">
		{% block content %}

		{% endblock %}
	    </div>

            <!-- javascript -->
	    {% block js %}	    
	    <script src= {% static "js/fastclick.js" %}></script>
	    <script src= {% static "js/foundation.min.js" %}></script>
	    <script src= {% static "js/angular.min.js" %}></script>
	    <script> $(document).foundation();</script>
	    {% endblock js %}
	</body>
</html>

APHive/APHive/templates/APHive/navbar.html
{% load staticfiles %}

<div class="contain-to-grid sticky primary-color-bg">
<nav class="top-bar primary-color-bg" data-topbar role="navigation" id="navbar">
	<div class="row collapse">
	<div class="small-12 column">	
	<ul class="title-area">
		<li class="name">
			<h1><a href="#">APHive</a></h1>
		</li>
		<li class="has-form">
			<form class="row collapse">
				<div class="large-8 small-9 columns">
					<input type="text" placeholder="Search APIs" id="search_box">
				</div>
				<div class="large-4 small-3 columns">
					<button type="submit" class="success button expand">Search</button>
				</div>
			</form>
		</li>
	</ul>
	</div>
	</div>
</nav>
</div>
<script src= {% static "APHive/js/navbar.js" %}></script>

APHive/apis/templates/api_endpoints.html
<h2>Endpoints go here</h2>
<ul class="accordion" data-accordion>
  <li class="accordion-navigation">
    <a href="#panel1a">Accordion 1</a>
    <div id="panel1a" class="content active">
      Panel 1. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dlore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </div>
  </li>
  <li class="accordion-navigation">
    <a href="#panel2a">Accordion 2</a>
    <div id="panel2a" class="content">
      Panel 2. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dlore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </div>
  </li>
  <li class="accordion-navigation">
    <a href="#panel3a">Accordion 3</a>
    <div id="panel3a" class="content">
      Panel 3. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dlore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </div>
  </li>
</ul>
{% for endpoint in endpoints %}


{% empty %}


{% endfor %}

APHive/apis/templates/apis/api_detail.html
{% extends "base.html" %}
{% load review_tags %}
{% load staticfiles %}

{% block css %}
	{{ block.super }}
	<link rel="stylesheet" href={% static "apis/css/flipoutimage.css" %} />
	<link rel="stylesheet" href={% static "apis/css/apis.css" %} />
{% endblock css %}

{% block title %}
	{{ api.title  }}
{% endblock %}

{% block content %}	
	<div class="row">
		{% include "preview_api.html" with api=api %}
	</div>
	<div class="row collapse">
		<div class="small-12 column">
			<p style="margin: 12px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ api.full_desc }}<p>
		</div>
	</div>
	<div class="row collapse">
		<hr class="primary-color-outline" />
	</div>

	<div class="row collapse">
		<ul class="tabs" data-tab role="tablist" data-options="deep_linking:true">
			<li class="tab-title active">
				<a href="#Endpoints" class="tab-header" tabindex=0>Endpoints</a>
			</li>
			<li class="tab-title">
				<a href="#Reviews" class="tab-header" tabindex=0>Reviews</a>
			</li>
			<li class="tab-title">
				<a href="#Clients" class="tab-header" tabindex=0>Clients</a>
			</li>
		</ul>
		<div class="tabs-content primary-color-outline section-holder">
			<section role="tabpanel" aria-hidden="false" class="content active" id="Endpoints">
				{% include "api_endpoints.html" with endpoints=endpoints %}
			</section>
			<section role="tabpanel" aria-hidden="true" class="content" id="Reviews">
				{% reviews_for_api api_id=api.id %}
			</section>
			<section role="tabpanel" aria-hidden="true" class="content" id="Clients">
				<h2>Fourth panel content goes here...</h2>
			</section>
		</div>
	</div>
{% endblock %}

{% block js %}
	{{ block.super }}
	<script src= {% static "reviews/js/reviews.js" %}></script>
{% endblock js %}

APHive/apis/templates/apis/api_index.html
{% extends "base.html" %}

{% block title %}APIs Home{% endblock %}

{% block content %}
	{% include "api_set.html" with apis=apis %}
{% endblock content %}

APHive/apis/templates/apis/api_set.html
{% load staticfiles %}

<link rel="stylesheet" href={% static "apis/css/flipoutimage.css" %} />
{% for api in apis %}
	{% if not forloop.counter|divisibleby:2 %} 
		{% if forloop.counter > 1 %}</div>{% endif %}
		<div class="row collapse">	
	{% endif %}
		<div class="small-12 large-6 column">
			{% include "preview_api.html" with api=api %}
		</div>
{% empty %}
	<h1> No APIs :(<h2>
{% endfor %}
</div>

APHive/apis/templates/apis/preview_api.html
<div class="service" onclick="location.href='{% url 'apis:detail' api.id %}';">
	<div class="service-icon-box">
		<img src={{ api.icon.url }} alt={{ api.title }} class="service-icon">
	</div>
	<h2 class="service-heading">{{ api.title }}</h2>
	<a class="service-heading primary-color" href="{% url 'members:detail' api.author.id %}">{{ api.author.full_name }}</a>
	<p class="service-description">
		{% block hover_text %} 	
		{{ api.brief_desc }}
		{% endblock hover_text %} 	
	</p>
</div>

APHive/members/templates/members/member_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{{ member.full_name }}{% endblock %}

{% block content %}	
	<link rel="stylesheet" href={% static "members/css/members.css" %} />
	<link rel="stylesheet" href={% static "members/css/iconanims.css" %} />
	<link rel="stylesheet" href={% static "members/css/chart.css" %} />
	<div class="row collapse" >
		<div class="small-6 large-2 column">
			<img src="https://pbs.twimg.com/profile_images/1357505418/stickman_prof_pic.png" class="member-photo primary-color-outline" />
		</div>
		<div class="small-6 large-5 column">
			<h3>{{ member.full_name }}</h3>
			<div class="row collapse">
				<div class="small-12 large-12 column icon-holder">
				<a href="#" class="icon-button twitter icon-content">
				  <i class="fi-social-twitter"></i><span></span>
				</a>
				</div>
			</div>
		</div>
		<div class="small-12 large-5 column">
	
		</div>
	</div>
	<div class="row collapse">
		<hr class="primary-color-outline" />
	</div>
	<div class="row collapse">
		{% include "api_set.html" with apis=apis %}
	</div>
{% endblock %}

APHive/reviews/templates/reviews/review_detail.html
<div class="row">
	<div class="small-9 column review-holder">	
		<div>
		<a href="{% url 'members:detail' review.writer.id %}" class="member-link primary-color">{{review.writer.full_name}}</a>
		<span class="submitted-date">&nbsp;- {{review.submitted}}</span>
		</div>
		<p class="review-text">{{ review.text }}</p>
	</div>
	<div class="small-3 column thumbs-holder">
		{% if review.usability == True %}
			<h5>usable  <span class="like"><i class="fi-like"></i></span></h5>
		{% elif review.usability == False %}
			<h5>usable  <span class="dislike"><i class="fi-dislike"></i></span></h5>
		{% else %}
			<h5>usable  --</h5>
		{% endif %}
		{% if review.documentation == True %}
			<h5>docs  <span class="like"><i class="fi-like"></i></span></h5>
		{% elif review.documentation == False %}
			<h5>docs  <span class="dislike"><i class="fi-dislike"></i></span></h5>
		{% else %}
			<h5>docs  --</h5>
		{% endif %}
		{% if review.reliability == True %}
			<h5>reliable  <span class="like"><i class="fi-like"></i></span></h5>
		{% elif review.reliability == False %}
			<h5>reliable  <span class="dislike"><i class="fi-dislike"></i></span></h5>
		{% else %}
			<h5>reliable  --</h5>
		{% endif %}		
	</div>

</div>

APHive/reviews/templates/reviews/review_index.html
{% load staticfiles %}
<link rel="stylesheet" href={% static "reviews/css/reviews.css" %} />
<link rel="stylesheet" href={% static "reviews/css/chart.css" %} />

<div class="row collapse">
	<div class="large-12 columns">
	    <table class="chart">
	      <tbody>
		<tr>
		  <td>
		    <p class="percentage">{{ usable_percent }}%</p>
		  </td>
		  <td class="chart">
		    of users found this easy to use
		    <div class="barchart">
		      <span class="meter" style="width: {{ usable_percent }}%"></span>
		    </div>
		  </td>
		</tr>
		<tr>
		  <td>
		    <p class="percentage">{{ doc_percent }}%</p>
		  </td>
		  <td class="chart">
		    of users said the API had good documentation
		    <div class="barchart">
		      <span class="meter" style="width: {{ doc_percent }}%"></span>
		    </div>
		  </td>
		</tr>
		<tr>
		  <td>
		    <p class="percentage">{{ reliable_percent }}%</p>
		  </td>
		  <td class="chart">
		    of users said the API is reliable
		    <div class="barchart">
		      <span class="meter" style="width: {{ reliable_percent }}%"></span>
		    </div>
		  </td>
		</tr>
	      </tbody>
	    </table>
	  </div>
	</div>
<hr class="primary-color-outline" />
<form  method="post" action="" class="row collapse" name="form">
	<div class="small-12 large-6 column">
		 <textarea rows="8" cols="50" maxlength="500" placeholder="what did you think? Leave your comments here." class="review-input" id="review_text"></textarea> 
	</div>
	<div class="small-12 large-6 column">
	<table class="selection-table">
		<tr>
			<td><h5 class="show-for-small-only">Usable</h5><h5 class="show-for-medium-up">Usability</h5></td>
			<td>&nbsp;<i class="use-one fi-like selector" id="use_like"></i>&nbsp;
			    &nbsp;<span class="use-two selector review-underline" id="use_meg">--</span>&nbsp;
			    &nbsp;<i class="use-three fi-dislike selector" id="use_dislike"></i>&nbsp;
			    <td>
		</tr>
		<tr>
			<td><h5 class="show-for-small-only">Docs</h5><h5 class="show-for-medium-up">Documentation</h5></td>			<td>&nbsp;<i class="docs-one fi-like selector" id="docs_like"></i>&nbsp;
			    &nbsp;<span class="docs-two selector review-underline" id="docs_meh">--</span>&nbsp;
			    &nbsp;<i class="docs-three fi-dislike selector" id="docs_dislike"></i>&nbsp;
			    <td>
		</tr>
		<tr>
			<td><h5 class="show-for-small-only">Reliable</h5><h5 class="show-for-medium-up">Reliability</h5></td>
			<td>&nbsp;<i class="rel-one fi-like selector" id="rel_like"></i>&nbsp;
			    &nbsp;<span class="rel-two selector review-underline" id="rel_meh">--</span>&nbsp;
                            &nbsp;<i class="rel-three fi-dislike selector" id="rel_dislike"></i>&nbsp;
			    <td>
		</tr>
	</table>
	<input type="submit" class="button expand submit-review secondary-color-bg" ng-disabled="!form.$dirty" value="Submit Review" style="margin-right: 20px; margin-top: 12px"></input>
	</div>
</form>
<hr class="primary-color-outline" />
<div class="row collapse reviews-holder" >
	{% for review in reviews %}
		{% include "review_detail.html" with review=review %}
		<hr class="primary-color-outline" />
	{% empty %}
		<h2>No reviews submitted yet</h2>
	{% endfor %}
</div>